version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: entity_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345qwert
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
